### PR TITLE
Csrf fix

### PR DESCRIPTION
**Pull request by Skibo555**
refactor the code to eliminate the CSRF warning on the pages.

### CODE REVIEW

**Comment by Skibo555** [comment]
I think I don't have the rights to resolve conflicts, I tried to merge the branches on locally before I make a PR to resolve any conflicts that may arise but I was not able to do it. I got this message on the terminal "merge: upstream/CSRF-fix - not something we can merge"

**Comment by Skibo555** [comment]
@isatyamks Please, you need to look into this conflict, I think I don't have the rights to resolve it myself. The issue is fixed now.

**Comment by isatyamks** [comment]
Hi @Skibo555, the codebase has been updated, and your pull request has some conflicting files. Unfortunately, I can't merge it as is. Could you please resolve the conflicts or submit a new pull request?

**Comment by Skibo555** [comment]
Hi @isatyamks, I will submit another PR.

**Pull request closed without merging**
